### PR TITLE
Created initial set of files for GitHub repo.

### PR DESCRIPTION
**Pull request by tnabtaf**
### Description

Created initial set of files for GitHub repo.

Includes
* CODE_OF_CONDUCT.md (just points to conda organization CoC)
* CONTROBUTING.md (a list of ways to contribute)
* GOVERNANCE.md (a few items for this team, with link to conda Organization governance doc.
* README.md (repo home page)

I think the only potentially controversial things are in the Governance doc.

### CODE REVIEW

**Review by jezdez — APPROVED** [review]

**Comment by kenodegard** [comment]
I suggest we sync the CoC.md from conda/infra instead

**Comment by tnabtaf** [comment]
@kenodegard Why?

**Comment by kenodegard** [comment]
Bc it's the same file and one less file to worry about updating if any changes are necessary, we do this same syncing for all other repos in the conda org:

- https://github.com/conda/infra/blob/main/CODE_OF_CONDUCT.md
- https://github.com/conda/conda/blob/main/CODE_OF_CONDUCT.md
- https://github.com/conda/conda-build/blob/main/CODE_OF_CONDUCT.md
- etc.

All we have to do is add `conda/communications` [here](https://github.com/conda/infra/blob/main/.github/sync/config.yml#L102-L128)

**Comment by tnabtaf** [comment]
Aha!  Thank you.  I will update the PR.

**Pull request merged**
